{
  "type": "subproject",
  "default-target": "make-keywords",
  "targets": [
    {
      "type": "executable",
      "name": "make-keywords",
      "sources": [
        "make-keywords.c",
        "../../library/hash.c"
      ]
    }
  ]
}
