#!/bin/sh

if [ ! -d dist ] ; then
    mkdir dist
fi

if [ ! -x dist/build ] || [ tools/build/build.c -nt dist/build ] ; then
    clang -O3 -o dist/build tools/build/build.c
fi

if [ -x dist/build ] && [ dist/build -nt tools/build/build.c ] ; then
    exec dist/build $@
else
    echo "Can't build the build tool!"
fi

